/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Operational Climate Command Center Palette
        base: "#090A0B",
        ops: {
          base: "#090A0B",
          surface1: "#101214",
          surface2: "#141719",
          surface3: "#181B1E",
          borderSubtle: "rgba(255,255,255,0.06)",
          borderDefault: "rgba(255,255,255,0.10)",
          textPrimary: "#F3F4F6",
          textSecondary: "#8B9299",
          textMuted: "#5F666D",
          thermal: "#F28B62",
          thermalHot: "#FF6B45",
          cool: "#43D6B5",
          critical: "#FF453A",
        },
        "surface": "#090A0B",
        "surface-container-lowest": "#090A0B",
        "surface-container-low": "#101214",
        "surface-container": "#141719",
        "surface-container-high": "#181B1E",
        "surface-container-highest": "#22262B",
        "on-surface": "#F3F4F6",
        "on-surface-variant": "#8B9299",
        "outline": "#5F666D",
        "outline-variant": "rgba(255,255,255,0.06)",
        "primary": "#F28B62",
        "primary-container": "#F28B62",
        "on-primary-container": "#090A0B",
        "secondary": "#8B9299",
        "tertiary": "#43D6B5",
        "tertiary-container": "#101214",
        "error": "#FF453A",
        "error-container": "#2A1211",

        // Aliases
        canvas: "#090A0B",
        panel: "#101214",
        panelSubtle: "#141719",
        borderPrimary: "rgba(255,255,255,0.10)",
        accent: {
          DEFAULT: "#F28B62",
          hover: "#FF6B45",
        },
        trajectory: {
          emerging: "#ef4444",
          persistent: "#D97757",
          temporary: "#eab308",
          improving: "#10b981",
          watch: "#64748b",
        },
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-md": "0.75rem",
        "space-sm": "0.5rem",
        "gutter-mobile": "1rem",
        "space-base": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "header-height": "3.5rem",
        "space-2xl": "3rem",
        "space-2xs": "0.125rem",
        "space-3xl": "4rem",
        "gutter-desktop": "1.5rem",
        "space-xs": "0.25rem",
        "sidebar-width": "16rem"
      },
      fontFamily: {
        "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "code-sm": ["'JetBrains Mono'", "monospace"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-xl": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"]
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.005em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-xl-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "code-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
};
