/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Operational Earth & Sage Palette
        base: "#0D0F11",
        ops: {
          base: "#0D0F11",
          surface1: "#15181B",
          surface2: "#1B1F23",
          surface3: "#22262B",
          borderSubtle: "rgba(255,255,255,0.07)",
          borderDefault: "rgba(255,255,255,0.12)",
          textPrimary: "#F3F4F6",
          textSecondary: "#94A3B8",
          textMuted: "#64748B",
          thermal: "#D97757",
          thermalHot: "#C86040",
          cool: "#48A982",
          critical: "#E11D48",
        },
        "surface": "#0D0F11",
        "surface-container-lowest": "#0D0F11",
        "surface-container-low": "#15181B",
        "surface-container": "#1B1F23",
        "surface-container-high": "#22262B",
        "surface-container-highest": "#2B3037",
        "on-surface": "#F3F4F6",
        "on-surface-variant": "#94A3B8",
        "outline": "#64748B",
        "outline-variant": "rgba(255,255,255,0.07)",
        "primary": "#D97757",
        "primary-container": "#D97757",
        "on-primary-container": "#0D0F11",
        "secondary": "#94A3B8",
        "tertiary": "#48A982",
        "tertiary-container": "#15181B",
        "error": "#E11D48",
        "error-container": "#2A1215",

        // Aliases
        canvas: "#0D0F11",
        panel: "#15181B",
        panelSubtle: "#1B1F23",
        borderPrimary: "rgba(255,255,255,0.12)",
        accent: {
          DEFAULT: "#D97757",
          hover: "#C86040",
        },
        trajectory: {
          emerging: "#E11D48",
          persistent: "#D97757",
          temporary: "#D97706",
          improving: "#48A982",
          watch: "#64748B",
        },
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-md": "0.75rem",
        "space-sm": "0.5rem",
        "gutter-mobile": "1rem",
        "space-base": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "header-height": "3.5rem",
        "space-2xl": "3rem",
        "space-2xs": "0.125rem",
        "space-3xl": "4rem",
        "gutter-desktop": "1.5rem",
        "space-xs": "0.25rem",
        "sidebar-width": "16rem"
      },
      fontFamily: {
        "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "code-sm": ["'JetBrains Mono'", "monospace"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-xl": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"]
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.005em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-xl-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "code-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
};
