/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#4edea3",
        "inverse-on-surface": "#1e1e1e",
        "surface-tint": "#ffb787",
        "on-surface": "#d4e4fa",
        "secondary-fixed": "#c4e7ff",
        "on-tertiary-fixed-variant": "#005236",
        "surface-container-highest": "#222222",
        "surface": "#000000",
        "on-primary-fixed-variant": "#723600",
        "primary": "#ffb787",
        "on-primary-container": "#592900",
        "surface-container-lowest": "#000000",
        "surface-variant": "#222222",
        "on-tertiary-container": "#003f29",
        "on-surface-variant": "#ddc1b1",
        "outline": "#a58c7d",
        "tertiary": "#4edea3",
        "tertiary-container": "#00b57d",
        "outline-variant": "#333333",
        "error": "#ffb4ab",
        "on-tertiary": "#003824",
        "surface-container-low": "#080808",
        "on-secondary-fixed-variant": "#004c69",
        "on-secondary": "#00354a",
        "on-tertiary-fixed": "#002113",
        "on-secondary-fixed": "#001e2c",
        "secondary-container": "#00a6e0",
        "inverse-primary": "#964900",
        "on-primary-fixed": "#311300",
        "primary-container": "#f38020",
        "secondary-fixed-dim": "#7bd0ff",
        "secondary": "#7bd0ff",
        "surface-bright": "#282828",
        "background": "#000000",
        "primary-fixed": "#ffdcc7",
        "tertiary-fixed": "#6ffbbe",
        "on-secondary-container": "#00374d",
        "surface-container": "#101010",
        "surface-container-high": "#181818",
        "on-primary": "#502400",
        "on-error": "#690005",
        "inverse-surface": "#d4e4fa",
        "surface-dim": "#000000",
        "on-background": "#d4e4fa",
        "primary-fixed-dim": "#ffb787",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",

        // Aliases
        canvas: "#000000",
        panel: "#101010",
        panelSubtle: "#080808",
        borderPrimary: "#222222",
        accent: {
          DEFAULT: "#f38020",
          hover: "#ea580c",
        },
        trajectory: {
          emerging: "#ef4444",
          persistent: "#f38020",
          temporary: "#eab308",
          improving: "#10b981",
          watch: "#64748b",
        }
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-md": "0.75rem",
        "space-sm": "0.5rem",
        "gutter-mobile": "1rem",
        "space-base": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "header-height": "3.5rem",
        "space-2xl": "3rem",
        "space-2xs": "0.125rem",
        "space-3xl": "4rem",
        "gutter-desktop": "1.5rem",
        "space-xs": "0.25rem",
        "sidebar-width": "16rem"
      },
      fontFamily: {
        "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "code-sm": ["'JetBrains Mono'", "monospace"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-xl": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"]
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.005em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-xl-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "code-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
};
